(function(){
"use strict";
var h=React.createElement,useEffect=React.useEffect,useMemo=React.useMemo,useState=React.useState;
function todayIso(){var d=new Date(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return d.getFullYear()+"-"+m+"-"+day;}
function money(v,c){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:c||"EUR"}).format(Number(v||0));}
function peopleText(arr){arr=arr||[];return arr.length===2?"François + Onja":(arr[0]==="Francois"?"François":(arr[0]||"Non affecté"));}
function categoryIcon(cat){return {Repas:"🍽️",Transport:"🚕","Hôtel":"🛏️",Visite:"🏛️",Shopping:"🛍️",Courses:"🛒",Autre:"✨"}[cat]||"✨";}
function dayLabel(v){var d=new Date(v+"T12:00:00");return new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"short"}).format(d);}

function AuthGate(props){var b=window.CycladesBackend,ss=useState(null),session=ss[0],setSession=ss[1],ls=useState(true),loading=ls[0],setLoading=ls[1],fs=useState({username:"",password:""}),form=fs[0],setForm=fs[1],es=useState(""),error=es[0],setError=es[1],bs=useState(false),busy=bs[0],setBusy=bs[1];function refresh(){if(!b||!b.configured()){setSession(null);setLoading(false);return;}b.getSession().then(function(r){setSession(r.session||null);}).catch(function(){setSession(null);}).finally(function(){setLoading(false);});}useEffect(function(){refresh();window.addEventListener("cyclades-auth-changed",refresh);return function(){window.removeEventListener("cyclades-auth-changed",refresh);};},[]);function submit(ev){ev.preventDefault();setBusy(true);setError("");b.signIn(form.username.trim(),form.password).then(function(r){setSession(r.session||null);}).catch(function(){setError("Identifiant ou mot de passe incorrect.");}).finally(function(){setBusy(false);});}if(!b||!b.configured())return props.children(null);if(loading)return h("div",{className:"backend-overlay backend-notice"},"Vérification de la session…");if(!session)return h("div",{className:"backend-overlay"},h("main",{className:"page auth-page"},h("section",{className:"auth-card"},h("span",{className:"eyebrow"},"Accès privé"),h("h1",null,"Cyclades"),h("p",null,"Connecte-toi pour accéder au voyage."),h("form",{onSubmit:submit,className:"auth-form"},h("label",null,"Identifiant",h("input",{type:"text",required:true,autoComplete:"username",autoCapitalize:"none",value:form.username,onInput:function(x){setForm({username:x.target.value,password:form.password});}})),h("label",null,"Mot de passe",h("input",{type:"password",required:true,autoComplete:"current-password",value:form.password,onInput:function(x){setForm({username:form.username,password:x.target.value});}})),error?h("div",{className:"form-error"},error):null,h("button",{type:"submit",disabled:busy},busy?"Connexion…":"Se connecter")))));return props.children(session);}

function ExpensesView(){
 var b=window.CycladesBackend,es=useState([]),expenses=es[0],setExpenses=es[1],fs=useState({amount:"",category:"Repas",description:"",expense_date:todayIso(),island:"",payment_method:"Carte",currency:"EUR",people:["Francois","Onja"]}),form=fs[0],setForm=fs[1],ss=useState(""),status=ss[0],setStatus=ss[1],ls=useState(true),loading=ls[0],setLoading=ls[1],as=useState(false),adding=as[0],setAdding=as[1],ps=useState(""),password=ps[0],setPassword=ps[1];
 function load(){setLoading(true);b.listExpenses().then(setExpenses).catch(function(err){setStatus(err.message||"Impossible de charger les dépenses.");}).finally(function(){setLoading(false);});}
 useEffect(load,[]);
 var recap=useMemo(function(){var r={global:0,Francois:0,Onja:0};expenses.forEach(function(item){var a=Number(item.amount||0),p=item.people||[];r.global+=a;if(p.length){var share=a/p.length;p.forEach(function(name){if(r[name]!==undefined)r[name]+=share;});}});return r;},[expenses]);
 var grouped=useMemo(function(){var out=[];expenses.forEach(function(item){var g=out.find(function(x){return x.date===item.expense_date;});if(!g){g={date:item.expense_date,total:0,items:[]};out.push(g);}g.total+=Number(item.amount||0);g.items.push(item);});return out;},[expenses]);
 function setFormPerson(name){var next=form.people.slice(),i=next.indexOf(name);if(i>=0){if(next.length===1)return;next.splice(i,1);}else next.push(name);setForm(Object.assign({},form,{people:next}));}
 function submit(ev){ev.preventDefault();setStatus("");b.addExpense(form).then(function(){setForm(Object.assign({},form,{amount:"",description:""}));setAdding(false);setStatus("Dépense ajoutée");load();}).catch(function(err){setStatus(err.message||"Enregistrement impossible.");});}
 function remove(id){if(!window.confirm("Supprimer cette dépense ?"))return;b.deleteExpense(id).then(load).catch(function(err){setStatus(err.message||"Suppression impossible.");});}
 function togglePerson(item,name){var next=(item.people||[]).slice(),i=next.indexOf(name);if(i>=0){if(next.length===1)return;next.splice(i,1);}else next.push(name);b.setExpensePeople(item.id,next).then(load).catch(function(err){setStatus(err.message||"Réaffectation impossible.");});}
 function changePassword(ev){ev.preventDefault();b.updatePassword(password).then(function(){setPassword("");setStatus("Mot de passe modifié");}).catch(function(err){setStatus(err.message||"Modification impossible.");});}
 var cats=["Repas","Transport","Hôtel","Visite","Shopping","Courses","Autre"];
 return h("main",{className:"page expenses-page"},
  h("header",{className:"expense-top"},h("div",null,h("span",{className:"eyebrow"},"Grèce · 2026"),h("h1",null,"Dépenses"),h("p",null,expenses.length+" dépenses enregistrées"))),
  h("section",{className:"balance-card"},h("span",null,"Total du voyage"),h("strong",null,money(recap.global)),h("div",{className:"balance-split"},h("div",null,h("small",null,"François"),h("b",null,money(recap.Francois))),h("div",null,h("small",null,"Onja"),h("b",null,money(recap.Onja))))),
  status?h("div",{className:"expense-toast",onClick:function(){setStatus("");}},status):null,
  h("section",{className:"expense-history"},h("div",{className:"section-title"},h("h2",null,"Activité"),h("button",{type:"button",onClick:load},"↻")),loading?h("p",{className:"muted"},"Chargement…"):null,!loading&&!expenses.length?h("div",{className:"empty-expenses"},h("span",null,"💶"),h("strong",null,"Aucune dépense"),h("p",null,"Ajoute la première dépense du voyage.")):null,
   grouped.map(function(group){return h("div",{className:"expense-day",key:group.date},h("div",{className:"expense-day-head"},h("span",null,dayLabel(group.date)),h("strong",null,money(group.total))),group.items.map(function(item){return h("article",{className:"expense-row",key:item.id},h("div",{className:"category-bubble"},categoryIcon(item.category)),h("div",{className:"expense-main"},h("strong",null,item.description||item.category),h("span",null,[item.category,item.island,item.payment_method].filter(Boolean).join(" · ")),h("div",{className:"allocation-buttons"},["Francois","Onja"].map(function(name){var active=(item.people||[]).indexOf(name)>=0;return h("button",{key:name,type:"button",className:active?"active":"",onClick:function(){togglePerson(item,name);}},name==="Francois"?"F":"O");}))),h("div",{className:"expense-row-side"},h("strong",null,money(item.amount,item.currency)),h("small",null,peopleText(item.people)),h("button",{type:"button",onClick:function(){remove(item.id);},"aria-label":"Supprimer"},"×")));}));})
  ),
  h("button",{className:"expense-fab",type:"button",onClick:function(){setAdding(true);}},h("span",null,"+")," Ajouter"),
  adding?h("div",{className:"expense-sheet-backdrop",onMouseDown:function(e){if(e.target===e.currentTarget)setAdding(false);}},h("form",{className:"expense-sheet",onSubmit:submit},h("div",{className:"sheet-handle"}),h("div",{className:"sheet-head"},h("div",null,h("span",{className:"eyebrow"},"Nouvelle dépense"),h("h2",null,"Ajouter")),h("button",{type:"button",onClick:function(){setAdding(false);}},"×")),h("label",{className:"amount-field"},h("span",null,"Montant"),h("div",null,h("input",{autoFocus:true,type:"number",min:"0.01",step:"0.01",required:true,inputMode:"decimal",placeholder:"0,00",value:form.amount,onInput:function(x){setForm(Object.assign({},form,{amount:x.target.value}));}}),h("b",null,"€"))),h("div",{className:"category-picker"},cats.map(function(cat){return h("button",{type:"button",key:cat,className:form.category===cat?"active":"",onClick:function(){setForm(Object.assign({},form,{category:cat}));}},h("span",null,categoryIcon(cat)),h("small",null,cat));})),h("label",{className:"sheet-input"},"Description",h("input",{type:"text",value:form.description,placeholder:"Dîner, taxi, musée…",onInput:function(x){setForm(Object.assign({},form,{description:x.target.value}));}})),h("div",{className:"sheet-grid"},h("label",{className:"sheet-input"},"Date",h("input",{type:"date",required:true,value:form.expense_date,onInput:function(x){setForm(Object.assign({},form,{expense_date:x.target.value}));}})),h("label",{className:"sheet-input"},"Lieu",h("input",{type:"text",value:form.island,placeholder:"Santorin…",onInput:function(x){setForm(Object.assign({},form,{island:x.target.value}));}}))),h("div",{className:"split-picker"},h("span",null,"Pour qui ?"),h("button",{type:"button",className:form.people.indexOf("Francois")>=0?"active":"",onClick:function(){setFormPerson("Francois");}},"François"),h("button",{type:"button",className:form.people.indexOf("Onja")>=0?"active":"",onClick:function(){setFormPerson("Onja");}},"Onja")),h("div",{className:"payment-row"},h("label",{className:"sheet-input"},"Paiement",h("select",{value:form.payment_method,onChange:function(x){setForm(Object.assign({},form,{payment_method:x.target.value}));}},["Carte","Espèces","Apple Pay","Autre"].map(function(i){return h("option",{key:i},i);})))),h("button",{className:"save-expense",type:"submit"},"Ajouter "+(form.amount?money(form.amount):"la dépense")))):null,
  h("details",{className:"expense-settings"},h("summary",null,"Réglages du compte"),h("form",{className:"password-form",onSubmit:changePassword},h("input",{type:"password",minLength:4,required:true,value:password,placeholder:"Nouveau mot de passe",onInput:function(x){setPassword(x.target.value);}}),h("button",{type:"submit"},"Modifier")),h("button",{className:"logout-btn",type:"button",onClick:function(){b.signOut();}},"Se déconnecter"))
 );
}
function installExpenseTab(){var nav=document.querySelector(".primary-tabs");if(!nav||nav.querySelector(".backend-expense-tab"))return;nav.classList.add("backend-four-tabs");var btn=document.createElement("button");btn.type="button";btn.className="backend-expense-tab";btn.textContent="Dépenses";btn.addEventListener("click",function(){window.dispatchEvent(new Event("cyclades:expenses-open"));});nav.appendChild(btn);}
function BackendShell(){var os=useState(false),open=os[0],setOpen=os[1];useEffect(function(){function show(){setOpen(true);}window.addEventListener("cyclades:expenses-open",show);return function(){window.removeEventListener("cyclades:expenses-open",show);};},[]);return h(AuthGate,null,function(session){if(session){var root=document.getElementById("root");if(root)root.classList.remove("backend-hidden");setTimeout(installExpenseTab,0);}return session&&open?h("div",{className:"backend-overlay expenses-overlay"},h("button",{className:"backend-overlay-close",type:"button",onClick:function(){setOpen(false);},"aria-label":"Fermer"},"×"),h(ExpensesView)):null;});}
function boot(){var mount=document.getElementById("backend-root");if(!mount)return;ReactDOM.createRoot(mount).render(h(BackendShell));var observer=new MutationObserver(installExpenseTab);observer.observe(document.body,{childList:true,subtree:true});setTimeout(installExpenseTab,200);}
window.CycladesBackendUI={AuthGate:AuthGate,ExpensesView:ExpensesView};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();